Create login page
spot-on-tracker/app pull request #13
Opened 2024-04-29 01:42 UTC by TiFurt

login page was create with auth service and alert service
![image](https://github.com/spot-on-tracker/app/assets/90806064/df860d0e-40be-4104-867f-7e6be897655e)
![image](https://github.com/spot-on-tracker/app/assets/90806064/8a20ca64-450e-4381-b333-dce6fb4c7da2)
![image](https://github.com/spot-on-tracker/app/assets/90806064/2763cd24-87ab-443d-923a-2a7ed23b9cea)

2024-04-29 11:06 UTC, Thentrax approved these changes

2024-04-29 11:07 UTC, Thentrax approved these changes

2024-04-29 11:43 UTC, biel-correa requested changes

2024-04-29 11:43 UTC, biel-correa commented on lib/main.dart
> +          secondary: ThemeColors.primary,
this's inverted, changed your emulator to dark mode so you can see

2024-04-29 11:43 UTC, biel-correa commented on lib/models/login_data.dart
why do you need all this?

2024-04-29 11:43 UTC, biel-correa commented on lib/pages/login_page/login_page.dart
> +        backgroundColor: ThemeColors.primary,
needing to set this means that the theme is missconfigured

2024-04-29 11:43 UTC, biel-correa commented on lib/pages/login_page/login_page.dart
add comma after every parameter, this helps the extension organize the code for us

2024-04-29 11:43 UTC, biel-correa commented on lib/pages/login_page/login_page.dart
> +                      ),
add validation to check if it's null

2024-04-29 11:43 UTC, biel-correa commented on lib/providers/alert_service.dart
> +          color: ThemeColors.secondary,
themeColors wont update when the user is on dark mode, get the ColorScheme from Theme.of(context)

2024-04-29 11:43 UTC, biel-correa commented on lib/providers/auth_service.dart
add comma to help auto formatting

2024-04-29 11:43 UTC, biel-correa commented on lib/widgets/common_button.dart
> +  TextStyle _getStyle(context) {
context not being used

2024-04-29 11:43 UTC, biel-correa commented on lib/widgets/common_button.dart
> +  BoxDecoration _getDecoration(context) {
context not being used

2024-04-29 11:43 UTC, biel-correa commented on lib/widgets/header_text.dart
add comma to help formatting

2024-04-29 11:43 UTC, biel-correa commented on lib/widgets/password_form_field.dart
> +  late final showPassword = createSignal(context, false);
never use final and late at the same time

2024-04-29 11:43 UTC, biel-correa commented on lib/widgets/password_form_field.dart
> +        ),
you can use an IconButton instead

2024-04-29 20:59 UTC, TiFurt commented on lib/main.dart
> +          secondary: ThemeColors.primary,
done

2024-04-29 20:59 UTC, TiFurt commented on lib/models/login_data.dart
removed

2024-04-29 20:59 UTC, TiFurt commented on lib/widgets/password_form_field.dart
> +        ),
done

2024-04-29 21:00 UTC, TiFurt commented on lib/pages/login_page/login_page.dart
> +        backgroundColor: ThemeColors.primary,
done

2024-04-30 11:48 UTC, biel-correa commented on lib/widgets/header_text.dart
> +  final Color? color;
add default valeu and remove `?`

2024-04-30 11:50 UTC, biel-correa commented on lib/widgets/password_form_field.dart
> +}
move method to class

2024-04-30 11:50 UTC, biel-correa commented on lib/widgets/password_form_field.dart
add commas where necessary and format file

2024-04-30 23:38 UTC, TiFurt commented on lib/widgets/header_text.dart
> +  final Color? color;
![image](https://github.com/spot-on-tracker/app/assets/90806064/9d6a76a8-6d48-4695-a529-ef0401c81fd8)
the ContextThemeColors is not a const, it returns the color based on the the Theme, and since it is a final variable I can not set when initializing, thats why I decided to let it be null and when I set the text color if this is null I will use the default one base on the ContextThemeColors

2024-05-02 12:58 UTC, biel-correa approved these changes

2024-05-02 13:01 UTC, merged