Create reset password page
spot-on-tracker/app pull request #15
Opened 2024-05-03 01:56 UTC by TiFurt

2024-05-03 01:57 UTC, TiFurt commented
Closes #14

2024-05-03 10:28 UTC, Thentrax approved these changes

2024-05-03 11:41 UTC, biel-correa requested changes

2024-05-03 11:41 UTC, biel-correa commented on lib/pages/login_page/login_page.dart
> +                            ),
use ParagraphText or extract it to a new Text widget, avoid creating TextStyle since it will be hard to maintain in the future

2024-05-03 11:41 UTC, biel-correa commented on lib/pages/reset_password_page/reset_password_page.dart
> +                    const EdgeInsets.symmetric(horizontal: 40, vertical: 30),
add comma at the end of vertical and format

2024-05-03 11:41 UTC, biel-correa commented on lib/pages/reset_password_page/reset_password_page.dart
> +      },
```suggestion
      (value) => _emailSended(context),
```

2024-05-03 11:41 UTC, biel-correa commented on lib/pages/reset_password_page/reset_password_page.dart
> +                  context, ModalRoute.withName(RouteNames.login)),
format

2024-05-04 15:38 UTC, biel-correa requested changes

2024-05-04 15:38 UTC, biel-correa commented on lib/widgets/paragraph_text.dart
> +        color: color ?? ContextThemeColors.onBackground,
Set this as the default value of the property

2024-05-04 15:46 UTC, Thentrax approved these changes

2024-05-04 17:24 UTC, TiFurt commented on lib/widgets/paragraph_text.dart
> +        color: color ?? ContextThemeColors.onBackground,
I can't use `ContextThemeColors` as a default value since it is not a constant, it gets the color theme based on the context

2024-05-04 18:33 UTC, biel-correa approved these changes

2024-05-04 19:00 UTC, merged